preprocess:
  ##########################
  # input
  split_dir: data/split
  test_size: 0.3
  face_reco_batch_size: 16

  # archive_dest: pipeline_outs/archive_tmp

  ###########################
  # output
  data_files_dir: pipeline_outs/faces
  train_data_files_dir: pipeline_outs/faces/train
  train_data_files_zip: pipeline_outs/faces/train.zip
  test_data_files_dir: pipeline_outs/faces/test
  test_data_files_zip: pipeline_outs/faces/test.zip

train:
  ################################
  # input
  train_data_files_dir: pipeline_outs/faces/train
  train_data_files_zip: pipeline_outs/faces/train.zip
  test_data_files_dir: pipeline_outs/faces/test
  test_data_files_zip: pipeline_outs/faces/test.zip

  model_criterion: CrossEntropy
  model_type: MobileNetV3
  model_params:
    pretrained: false
  optimizer_type: Adam
  optimizer_params:
    momentum: 0.9
    learning_rate: 0.001
  scheduler_type: ReduceLROnPlateau
  scheduler_params:
    step_size: 7
    patience: 7
    gamma: 0.1
    factor: 0.1
  
  input_size: 64
  epochs: 10
  batch_size: 1024
  n_workers: 8

  ################################
  # output
  model_dir: pipeline_outs/models
  model_file: pipeline_outs/models/latest-model.pth
  results_dir: pipeline_outs/results/
  train_results_file: pipeline_outs/results/train-results.json
  train_plots_file: pipeline_outs/results/train-plots.json
  test_results_file: pipeline_outs/results/test-results.json
  test_plots_file: pipeline_outs/results/test-plots.json
  losses_file: pipeline_outs/results/losses.json

# evaluate:
#   ################################
#   # input
#   data_file: pipeline_outs/split/test.csv.gz
#   model_file: pipeline_outs/models/best-model.joblib

#   ################################
#   # output
#   model_params_file: pipeline_outs/models/model-params.json
#   results_dir: pipeline_outs/results
#   results_file: pipeline_outs/results/test-results.json
#   prediction_results_file: pipeline_outs/results/predictions.csv
#   pr_curve_file: pipeline_outs/results/precision_recall_curve.csv